name: Deploy to Docker Hub
on: push
env:
  IMAGE_NAME: kueen/pcloud:arm32v7
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Log into registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      
      - name: Push image
        run: docker push $IMAGE_NAME
